//package com.example.HospitalManagement.Repository;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//import com.example.HospitalManagement.Entity.AnesthesiaRecord;
//import org.springframework.data.jpa.repository.JpaRepository;
//import java.util.List;
//
//public interface AnesthesiaRecordRepository extends JpaRepository<AnesthesiaRecord, Long> {
//    List<AnesthesiaRecord> findByProcedureId(Long procedureId);
//    List<AnesthesiaRecord> findByAnesthesiologistId(Long anesthesiologistId);
//}
