//package com.example.HospitalManagement.Repository;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//import com.example.HospitalManagement.Entity.Task;
//import org.springframework.data.jpa.repository.JpaRepository;
//import java.util.List;
//
//public interface TaskRepository extends JpaRepository<Task, Long> {
//    List<Task> findByProcedureId(Long procedureId);
//    List<Task> findByAssignedRole(String assignedRole);
//}
//
