//package com.example.HospitalManagement.Entity;
//
//import jakarta.persistence.*;
//
//import java.sql.Date;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//@Entity
//@Table(name = "anesthesia_records")
//public class AnesthesiaRecord {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    @ManyToOne
//    @JoinColumn(name = "procedure_id", nullable = false)
//    private Procedure procedure;
//
//    @ManyToOne
//    @JoinColumn(name = "anesthesiologist_id", nullable = false)
//    private User anesthesiologist;
//
//    @Column(nullable = false)
//    private String anesthesiaType;
//
//    public Date getAdministeredAt() {
//        return administeredAt;
//    }
//
//    public void setAdministeredAt(Date administeredAt) {
//        this.administeredAt = administeredAt;
//    }
//
//    public String getAnesthesiaType() {
//        return anesthesiaType;
//    }
//
//    public void setAnesthesiaType(String anesthesiaType) {
//        this.anesthesiaType = anesthesiaType;
//    }
//
//    public User getAnesthesiologist() {
//        return anesthesiologist;
//    }
//
//    public void setAnesthesiologist(User anesthesiologist) {
//        this.anesthesiologist = anesthesiologist;
//    }
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getNotes() {
//        return notes;
//    }
//
//    public void setNotes(String notes) {
//        this.notes = notes;
//    }
//
//    public Procedure getProcedure() {
//        return procedure;
//    }
//
//    public void setProcedure(Procedure procedure) {
//        this.procedure = procedure;
//    }
//
//    private String notes;
//
//    @Column(nullable = false)
//    private Date administeredAt;
//}
