//package com.example.HospitalManagement.Entity;
//
//import jakarta.persistence.*;
//
//import java.util.Date;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//@Entity
//@Table(name = "patients")
//public class Patient {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    public Date getDateOfBirth() {
//        return dateOfBirth;
//    }
//
//    public void setDateOfBirth(Date dateOfBirth) {
//        this.dateOfBirth = dateOfBirth;
//    }
//
//    public String getGender() {
//        return gender;
//    }
//
//    public void setGender(String gender) {
//        this.gender = gender;
//    }
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getMedicalRecordNumber() {
//        return medicalRecordNumber;
//    }
//
//    public void setMedicalRecordNumber(String medicalRecordNumber) {
//        this.medicalRecordNumber = medicalRecordNumber;
//    }
//
//    public String getName() {
//        return name;
//    }
//
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    @Column(nullable = false)
//    private String name;
//
//    private Date dateOfBirth;
//    private String gender;
//    private String medicalRecordNumber;
//    // Add other patient-specific fields as needed
//}
