//package com.example.HospitalManagement.Entity;
//
//import jakarta.persistence.*;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//@Entity
//@Table(name = "procedure_team_assignments")
//public class ProcedureTeamAssignment {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    @ManyToOne
//    @JoinColumn(name = "procedure_id", nullable = false)
//    private Procedure procedure;
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public User getUser() {
//        return user;
//    }
//
//    public void setUser(User user) {
//        this.user = user;
//    }
//
//    public String getRoleInTeam() {
//        return roleInTeam;
//    }
//
//    public void setRoleInTeam(String roleInTeam) {
//        this.roleInTeam = roleInTeam;
//    }
//
//    public Procedure getProcedure() {
//        return procedure;
//    }
//
//    public void setProcedure(Procedure procedure) {
//        this.procedure = procedure;
//    }
//
//    @ManyToOne
//    @JoinColumn(name = "user_id", nullable = false)
//    private User user;
//
//    @Column(nullable = false)
//    private String roleInTeam; // leadnurse, anesthesiologist, consulting physician, etc.
//}
