//package com.example.HospitalManagement.Entity;
////
////import jakarta.persistence.*;
////
////import java.util.Date;
////
////// Code Generated by Sidekick is for learning and experimentation purposes only.
////@Entity
////@Table(name = "procedures")
////public class Procedure {
////    @Id
////    @GeneratedValue(strategy = GenerationType.IDENTITY)
////    private Long id;
////
////    @ManyToOne
////    @JoinColumn(name = "patient_id", nullable = false)
////    private Patient patient;
////
////    @ManyToOne
////    @JoinColumn(name = "lead_surgian_id", nullable = false)
////    private User leadSurgian;
////
////    public Long getId() {
////        return id;
////    }
////
////    public void setId(Long id) {
////        this.id = id;
////    }
////
////    public User getLeadSurgian() {
////        return leadSurgian;
////    }
////
////    public void setLeadSurgian(User leadSurgian) {
////        this.leadSurgian = leadSurgian;
////    }
////
////    public String getNotes() {
////        return notes;
////    }
////
////    public void setNotes(String notes) {
////        this.notes = notes;
////    }
////
////    public Patient getPatient() {
////        return patient;
////    }
////
////    public void setPatient(Patient patient) {
////        this.patient = patient;
////    }
////
////    public String getProcedureName() {
////        return procedureName;
////    }
////
////    public void setProcedureName(String procedureName) {
////        this.procedureName = procedureName;
////    }
////
////    public Date getScheduledAt() {
////        return scheduledAt;
////    }
////
////    public void setScheduledAt(Date scheduledAt) {
////        this.scheduledAt = scheduledAt;
////    }
////
////    @Column(nullable = false)
////    private String procedureName;
////
////    @Column(nullable = false)
////    private Date scheduledAt;
////
////    private String notes;
////}
//
//
//
//import jakarta.persistence.*;
//import java.util.Date;
//
//@Entity
//public class Procedure {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    private String procedureName;
//    private Date scheduledAt;
//
//    @ManyToOne
//    private Patient patient;
//
//    public Patient getPatient() {
//        return patient;
//    }
//
//    public void setPatient(Patient patient) {
//        this.patient = patient;
//    }
//
//    public User getAnesthesiologist() {
//        return anesthesiologist;
//    }
//
//    public void setAnesthesiologist(User anesthesiologist) {
//        this.anesthesiologist = anesthesiologist;
//    }
//
//
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public User getLeadNurse() {
//        return leadNurse;
//    }
//
//    public void setLeadNurse(User leadNurse) {
//        this.leadNurse = leadNurse;
//    }
//
//    public User getLeadSurgeon() {
//        return leadSurgeon;
//    }
//
//    public void setLeadSurgeon(User leadSurgeon) {
//        this.leadSurgeon = leadSurgeon;
//    }
//
//    public String getNotes() {
//        return notes;
//    }
//
//    public void setNotes(String notes) {
//        this.notes = notes;
//    }
//
//    public String getProcedureName() {
//        return procedureName;
//    }
//
//    public void setProcedureName(String procedureName) {
//        this.procedureName = procedureName;
//    }
//
//    public Date getScheduledAt() {
//        return scheduledAt;
//    }
//
//    public void setScheduledAt(Date scheduledAt) {
//        this.scheduledAt = scheduledAt;
//    }
//
//    private String notes;
//
//    @ManyToOne
//    private User leadSurgeon;
//
//    @ManyToOne
//    private User leadNurse;
//
//    @ManyToOne
//    private User anesthesiologist;
//
//    // Getters and setters
//}
