//package com.example.HospitalManagement.Entity;
//
//import jakarta.persistence.*;
//
//import java.sql.Date;
//
//// Code Generated by Sidekick is for learning and experimentation purposes only.
//@Entity
//@Table(name = "procedure_notes")
//public class ProcedureNote {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    @ManyToOne
//    @JoinColumn(name = "procedure_id", nullable = false)
//    private Procedure procedure;
//
//    @ManyToOne
//    @JoinColumn(name = "author_id", nullable = false)
//    private User author;
//
//    public User getAuthor() {
//        return author;
//    }
//
//    public void setAuthor(User author) {
//        this.author = author;
//    }
//
//    public Date getCreatedAt() {
//        return createdAt;
//    }
//
//    public void setCreatedAt(Date createdAt) {
//        this.createdAt = createdAt;
//    }
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getNote() {
//        return note;
//    }
//
//    public void setNote(String note) {
//        this.note = note;
//    }
//
//    public Procedure getProcedure() {
//        return procedure;
//    }
//
//    public void setProcedure(Procedure procedure) {
//        this.procedure = procedure;
//    }
//
//    @Column(nullable = false)
//    private String note;
//
//    @Column(nullable = false)
//    private Date createdAt;
//}
